app:
  auth:
    header-scheme-name: authorization
    token-type: Bearer
    access-secret: DeaguGreenArtAcademyClass502ForJavaSpringBoot
    accessTokenExpiry: 3_600_000 # 1시간
    refresh-secret: ForJavaSpringBootClass502DaeguGreenArtAcademy
    refreshTokenExpiry: 1_296_000_000 # 15일
    redis-access-black-key: "A-AT-BLACK"
    redis-refresh-key: "A-RT"
  oauth2:
    authorized-redirect-uris:
      - http://localhost:8080/oauth/redirect #카카카카카
      - http://192.168.0.207:8080/oauth/redirect

springboot:
  jwt:
    access-secret: DeaguGreenArtAcademyClass502ForJavaSpringBootaaaasdf
    refresh-secret: HelloWorldRefreshTokenCreateBySecretHaHaaasdfasdf
    header-scheme-name: authorization
    token-type: Bearer

spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: yummeal@naver.com
    password: ghost123!
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  main:
    allow-bean-definition-overriding: true


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
 #   url: jdbc:mariadb://localhost:3306/babymeal
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/team_a
    username: ${DB_USERNAME}
    password: ${DB_USERPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # Entity? ??? ?? ???? ???.
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 740674913997-bd78tt7qmh2vn0njsciroui23qk98650.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1420964125115360
            client-secret: 258a5df7657e4b2f666470e42350048f
            scope:
              - email
              - public_profile
          naver:
            client-id: Kc_XEjt7QCVTXFybbp3h
            client-secret: kSelcXBiP8
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          kakao:
            client-id: d0e4159691e49fbf5bbdbd05aa2cb44c
            client-secret: ysZmr4c6vFMfsoabmH2lxdowI0iHHyFp
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


# cors
cors:
  allowed-origins: 'http://localhost:8080'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600


  data:
    redis:
      host: ${DB_HOST}
      port: ${DB_REDISPORT}

# mybatis config
mybatis:
  type-aliases-package: com.green.babymeal
  mapper-locations: mapper/*.xml

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html


file:
  dir: /app/download



---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mariadb://localhost:3306/babyfood
    username: root
    password: green502
  sql:
    init:
      mode: always
      schema-locations: classpath:init/schema.sql
      data-locations: classpath:init/data.sql
---

spring:
  config:
    activate:
      on-profile: "prod"
  data:
    redis:
      host: 192.168.0.144
  datasource:
    url: jdbc:mariadb://192.168.0.144:3306/team_a
    username: team_a
  jpa:
    hibernate:
      ddl-auto: none
file:
  dir: /home/download
server:
  port: 8080

app:
  oauth2:
    authorized-redirect-uris:
      - http://192.168.0.144:5001/oauth/redirect
      - http://112.222.157.156:5001/oauth/redirect
